name: Build and update GitHub Pages

on:
  push:
    branches:
      - 'main'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install
        run: |
          yarn
      -
        name: Lint
        run: |
          yarn lint
      -
        name: Verify
        run: |
          yarn verify
      -
        name: Build
        run: |
          VERSION=v$(node -p "require('./package').version") COMMIT_HASH=$(git rev-parse --short HEAD) yarn build
      -
        name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v2
        with:
          pages_threshold: major_outage
      -
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: true
